# -*- coding: utf-8 -*-
"""13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBGjBFo8SQ2E4p4Z9bj_upNiWNOSMOHO
"""



"""Super, on va procéder en deux temps pour chaque jour :  

1. **Collecte ou préparation des données**  
2. **Gabarit graphique sous Matplotlib (style médiéval)**

On commence jour par jour. Je te propose qu’on commence par **Day 13 – Clusters | Poètes médiévaux**. Voici le plan :

---

## 🔮 **Day 13 – Clusters | Poètes médiévaux**

### 🎯 Objectif :
Créer une visualisation des relations thématiques entre poètes médiévaux — une sorte de clustering sémantique.

---

### 📦 Données à collecter :
| Poète | Langue | Région | Thèmes dominants | Genre | Dates |
|-------|--------|--------|------------------|--------|-------|
| Dante Alighieri | Italien | Florence | Amour, Religion, Politique | Homme | 1265–1321 |
| Hildegarde von Bingen | Latin | Germanie | Mystique, Médecine, Musique | Femme | 1098–1179 |
| Chrétien de Troyes | Français | Champagne | Chevalerie, Amour courtois | Homme | 1135–1190 |
| Ibn Hazm | Arabe | Espagne (Cordoue) | Philosophie de l'amour | Homme | 994–1064 |
| Béroul | Français | Normandie | Tristan & Iseult, Amour interdit | Homme | XIIe siècle |
| Marie de France | Français/Anglo-normand | Angleterre | Lais, Amour courtois, Féérie | Femme | XIIe siècle |
| Guido Guinizelli | Italien | Bologne | Dolce stil novo | Homme | 1230–1276 |

On peut classer les poètes par **thèmes dominants** et faire un clustering basé sur la **similitude de ces thèmes**.

---

### 🔗 Structure relationnelle à créer :
On va transformer les **thèmes** en variables binaires (1 si présent), et calculer une matrice de similarité (cosine ou jaccard), puis utiliser un **clustering hiérarchique** ou un **graph réseau**.

Souhaites-tu :
- A. Une **dendrogramme (hiérarchique)** des poètes ?
- B. Un **graph en réseau (networkx)** des relations entre poètes selon leurs thèmes ?

Et ensuite, veux-tu que je t’envoie un script Python avec ces données intégrées et le gabarit Matplotlib (avec style médiéval : police, bordure, fond parchemin, etc.) ?
"""

import matplotlib.pyplot as plt
import pandas as pd
from scipy.cluster.hierarchy import linkage, dendrogram
from sklearn.preprocessing import MultiLabelBinarizer
from matplotlib import font_manager
import matplotlib.patches as patches

# 📌 Données simplifiées
poets = [
    {"name": "Dante Alighieri", "themes": ["amour", "religion", "politique"]},
    {"name": "Hildegarde von Bingen", "themes": ["mystique", "médecine", "musique", "religion"]},
    {"name": "Chrétien de Troyes", "themes": ["chevalerie", "amour", "courtoisie"]},
    {"name": "Ibn Hazm", "themes": ["amour", "philosophie", "religion"]},
    {"name": "Béroul", "themes": ["amour", "tragédie", "légende"]},
    {"name": "Marie de France", "themes": ["amour", "féérie", "courtoisie"]},
    {"name": "Guido Guinizelli", "themes": ["amour", "dolce stil novo", "philosophie"]},
]

# 📊 Transformation en DataFrame
df = pd.DataFrame(poets)

# 🔄 Encodage binaire des thèmes
mlb = MultiLabelBinarizer()
themes_encoded = mlb.fit_transform(df["themes"])
df_encoded = pd.DataFrame(themes_encoded, columns=mlb.classes_, index=df["name"])

# 🔗 Clustering hiérarchique
linked = linkage(df_encoded, method='ward')

# 🎨 Dendrogramme avec style médiéval
fig, ax = plt.subplots(figsize=(10, 6))

# 👑 Fond parchemin
ax.set_facecolor('#f7f1d3')
fig.patch.set_facecolor('#e8dbc5')
ax.add_patch(patches.Rectangle((0, 0), 1, 1, transform=ax.transAxes,
                               facecolor='#f7f1d3', edgecolor='#8b5e3c', linewidth=10))

# 📜 Titre style ancien
plt.title("Clustering des poètes médiévaux", fontsize=16, fontweight='bold', family='serif', color='#5c3a21')

# 🌿 Dendrogramme
dendrogram(linked,
           labels=df["name"].values,
           orientation='top',
           distance_sort='descending',
           show_leaf_counts=True,
           color_threshold=10,
           leaf_font_size=10)

# 🎭 Ornementation
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.subplots_adjust(top=0.88)

# 🖼️ Affichage
plt.show()

"""Icônes ou lettrines : ajouter via matplotlib.offsetbox.AnnotationBbox ou plt.figimage des éléments illustratifs (ex: plume, croix, enluminure dans les coins).


"""

import matplotlib.pyplot as plt
import numpy as np

from matplotlib.cbook import get_sample_data
from matplotlib.offsetbox import (AnnotationBbox, DrawingArea, OffsetImage,
                                  TextArea)
from matplotlib.patches import Circle

fig, ax = plt.subplots()

# Define a 1st position to annotate (display it with a marker)
xy = (0.5, 0.7)
ax.plot(xy[0], xy[1], ".r")

# Annotate the 1st position with a text box ('Test 1')
offsetbox = TextArea("Test 1")

ab = AnnotationBbox(offsetbox, xy,
                    xybox=(-20, 40),
                    xycoords='data',
                    boxcoords="offset points",
                    arrowprops=dict(arrowstyle="->"),
                    bboxprops=dict(boxstyle="sawtooth"))
ax.add_artist(ab)

# Annotate the 1st position with another text box ('Test')
offsetbox = TextArea("Test")

ab = AnnotationBbox(offsetbox, xy,
                    xybox=(1.02, xy[1]),
                    xycoords='data',
                    boxcoords=("axes fraction", "data"),
                    box_alignment=(0., 0.5),
                    arrowprops=dict(arrowstyle="->"))
ax.add_artist(ab)

# Define a 2nd position to annotate (don't display with a marker this time)
xy = [0.3, 0.55]

# Annotate the 2nd position with a circle patch
da = DrawingArea(20, 20, 0, 0)
p = Circle((10, 10), 10)
da.add_artist(p)

ab = AnnotationBbox(da, xy,
                    xybox=(1., xy[1]),
                    xycoords='data',
                    boxcoords=("axes fraction", "data"),
                    box_alignment=(0.2, 0.5),
                    arrowprops=dict(arrowstyle="->"),
                    bboxprops=dict(alpha=0.5))

ax.add_artist(ab)

# Annotate the 2nd position with an image (a generated array of pixels)
arr = np.arange(100).reshape((10, 10))
im = OffsetImage(arr, zoom=2)
im.image.axes = ax

ab = AnnotationBbox(im, xy,
                    xybox=(-50., 50.),
                    xycoords='data',
                    boxcoords="offset points",
                    pad=0.3,
                    arrowprops=dict(arrowstyle="->"))

ax.add_artist(ab)

# Annotate the 2nd position with another image (a Grace Hopper portrait)
with get_sample_data("grace_hopper.jpg") as file:
    arr_img = plt.imread(file)

imagebox = OffsetImage(arr_img, zoom=0.2)
imagebox.image.axes = ax

ab = AnnotationBbox(imagebox, xy,
                    xybox=(120., -80.),
                    xycoords='data',
                    boxcoords="offset points",
                    pad=0.5,
                    arrowprops=dict(
                        arrowstyle="->",
                        connectionstyle="angle,angleA=0,angleB=90,rad=3")
                    )

ax.add_artist(ab)

# Fix the display limits to see everything
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)

plt.show()

!python -m spacy download fr_core_news_md

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

import spacy
nlp = spacy.load("fr_core_news_md")  # Ou en_core_web_md pour l'anglais

# 📦 Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import seaborn as sns

# 📝 Données fictives
data = {
    'poet': ['Marie de France'] * 4 + ['Anne Comnène'] * 4 + ['Hildegarde von Bingen'] * 4,
    'poem': ['Le Lai du Chèvrefeuille'] * 4 + ['Alexiade'] * 4 + ['O vis aeternitatis'] * 4,
    'text': [
        "Dans la forêt je vis l'amour",  # Marie
        "Sous le chèvrefeuille s'endort l'espoir",
        "Le chevalier soupire et part",
        "L'arbre enlace le destin",
        "L'empereur tombe sous la plume",  # Anne
        "J'écris pour mémoire et pour justice",
        "Les batailles sont plus que des récits",
        "Une femme voit et témoigne",
        "Ô souffle divin, ô feu sacré",  # Hildegarde
        "La lumière chante en mon cœur",
        "Les visions s'élèvent vers l'Éternel",
        "Mon chant est une prière céleste"
    ]
}
df = pd.DataFrame(data)

# ✨ TF-IDF vectorisation
vectorizer = TfidfVectorizer(max_features=100)
X = vectorizer.fit_transform(df['text']).toarray()

# 🔻 Réduction de dimension (PCA)
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)
df['x'] = X_reduced[:, 0]
df['y'] = X_reduced[:, 1]

# 🎯 Clustering
kmeans = KMeans(n_clusters=3, random_state=0)
df['cluster'] = kmeans.fit_predict(X_reduced)

# 🎨 Connected Scatterplot
fig, ax = plt.subplots(figsize=(10, 6))

# Tracer les chemins poétiques
for (poet, poem), group in df.groupby(['poet', 'poem']):
    ax.plot(group['x'], group['y'], alpha=0.4, linestyle='--', linewidth=1)
    sc = ax.scatter(group['x'], group['y'],
                    c=group['cluster'], cmap='tab10', label=poet, edgecolor='black', s=100)

# Annotations (facultatif)
for i, row in df.iterrows():
    ax.annotate(f"{i+1}", (row['x'], row['y']), fontsize=8, alpha=0.6)

ax.set_title("Parcours poétiques de Marie, Anne & Hildegarde", fontsize=14)
ax.set_xlabel("PCA Dimension 1")
ax.set_ylabel("PCA Dimension 2")
plt.legend(title="Poétesse")
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import plotly.express as px
import plotly.graph_objects as go

# 🎭 Données fictives
data = {
    'poet': ['Marie de France'] * 4 + ['Anne Comnène'] * 4 + ['Hildegarde von Bingen'] * 4,
    'poem': ['Le Lai du Chèvrefeuille'] * 4 + ['Alexiade'] * 4 + ['O vis aeternitatis'] * 4,
    'text': [
        "Dans la forêt je vis l'amour",
        "Sous le chèvrefeuille s'endort l'espoir",
        "Le chevalier soupire et part",
        "L'arbre enlace le destin",
        "L'empereur tombe sous la plume",
        "J'écris pour mémoire et pour justice",
        "Les batailles sont plus que des récits",
        "Une femme voit et témoigne",
        "Ô souffle divin, ô feu sacré",
        "La lumière chante en mon cœur",
        "Les visions s'élèvent vers l'Éternel",
        "Mon chant est une prière céleste"
    ]
}
df = pd.DataFrame(data)

# 🔤 TF-IDF vectorisation
vectorizer = TfidfVectorizer(max_features=100)
X = vectorizer.fit_transform(df['text']).toarray()

# 🔻 PCA
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)
df['x'] = X_reduced[:, 0]
df['y'] = X_reduced[:, 1]

# 🎯 Clustering
kmeans = KMeans(n_clusters=3, random_state=42)
df['cluster'] = kmeans.fit_predict(X_reduced)

# 📈 Connected scatterplot avec Plotly
fig = go.Figure()

# Lignes connectées par poème
for (poet, poem), group in df.groupby(['poet', 'poem']):
    fig.add_trace(go.Scatter(
        x=group['x'],
        y=group['y'],
        mode='lines+markers',
        name=f"{poet} — {poem}",
        text=group['text'],
        marker=dict(size=10, color=group['cluster'], colorscale='Viridis', line=dict(color='black', width=1)),
        line=dict(dash='dash', width=1),
        hovertemplate="<b>%{text}</b><br>Poète : " + poet + "<br>Poème : " + poem + "<extra></extra>"
    ))

# Mise en page
fig.update_layout(
    title="Connected Scatterplot des Poèmes Médiévaux",
    xaxis_title="PCA - Axe 1 (style / thème)",
    yaxis_title="PCA - Axe 2 (style / thème)",
    legend_title="Poète & Poème",
    template="plotly_white",
    width=900,
    height=600
)

fig.show()

"""corpus/

├── Marie_de_France_Lai_du_Chevrefeuille.txt

├── Anne_Comnene_Alexiade.txt

├── Hildegarde_O_Vis_Aeternitatis.txt

"""

from google.colab import drive
drive.mount('/content/drive')

pip install sacremoses sentencepiece transformers

from transformers import pipeline
import pandas as pd

"""1. COLLECT DATA TEXT + SENTIMENT ANALYSIS NLP"""

# Charger le poème à partir d'un fichier texte
with open('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Marie_de_France_Lai_du_Chevrefeuille.txt', 'r', encoding='utf-8') as file:
    Marie_de_France_Lai_du_Chevrefeuille = file.read()
#print(Marie_de_France_Lai_du_Chevrefeuille[:1500])

# Tokenisation et nettoyage
import re
cleaned_poem_MF = re.sub(r'\s+', ' ', Marie_de_France_Lai_du_Chevrefeuille).strip()  # Nettoyage des espaces multiples
cleaned_poem_MF = re.sub(r'[^\w\s,.\-:;!?«»]', '', Marie_de_France_Lai_du_Chevrefeuille)  # Garder des signes de ponctuation spécifiques


# Vectorisation (par exemple, TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=100)
tfidf_matrix = vectorizer.fit_transform([cleaned_poem_MF])

# Appliquer l'analyse NLP pour émotions et thèmes
#from transformers import pipeline
#emotion_model = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", top_k=1)
#emotion = emotion_model(cleaned_poem_MF)
#print(f"Emotion détectée : {emotion}") #Emotion détectée : [[{'label': 'neutral', 'score': 0.26447024941444397}]]

#1. Diviser chaque poème ligne par ligne
lines = cleaned_poem_MF.split('\n')  # Sépare les vers
lines = [line.strip() for line in lines if line.strip() != '']  # Supprime les lignes vides

#2. Appliquer un modèle NLP d’analyse d’émotions à chaque ligne
from transformers import pipeline

# Traduction FR → EN
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en", device=-1)

# Analyse émotionnelle (anglais) sans warning
emotion_model = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    top_k=1,
    device=-1
)

def translate_line(line):
    # on ne traduit que si la ligne n’est pas vide
    if not line.strip():
        return ""
    # retour = liste d’un seul dict {‘translation_text’: ...}
    result = translator(line, max_length=200)[0]
    return result['translation_text']

emotion_data = []
for i, line in enumerate(lines):
    en_line = translate_line(line)

    raw = emotion_model(en_line)    # peut-être [[{…}]] ou [{…}]
    first = raw[0]
    result = first[0] if isinstance(first, list) else first

    emotion_data.append({
        'line_number': i,
        'fr_text': line,
        'en_text': en_line,
        'label': result['label'],
        'score': result['score']
    })
#result = emotion_model(en_line)[0][0] if isinstance(emotion_model(en_line)[0], list) else emotion_model(en_line)[0]

#3. Convertir en DataFrame
import pandas as pd
df_emotions_MF = pd.DataFrame(emotion_data)
print_df = df_emotions_MF.sample(3)
print_df

# Create the figure
fig, ax = plt.subplots(figsize=(12, 3))
ax.axis('off')
table = ax.table(cellText=print_df.values, colLabels=print_df.columns, rowLabels=print_df.index,
                 cellLoc='center', loc='center')
table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 1.2)

# Save as image
plt.savefig("df_emotions_MF.jpg", dpi=300, bbox_inches='tight')

#4. Encodage des émotions pour les scatter plots
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_emotions_MF['emotion_encoded'] = label_encoder.fit_transform(df_emotions_MF['label'])

#5. Créer un connected scatter plot (matplotlib ou plotly)

import plotly.express as px

fig = px.scatter(df_emotions_MF,
                 x='line_number',
                 y='emotion_encoded',
                 text='label',
                 title="Évolution émotionnelle du poème",
                 labels={'line_number': "Numéro de ligne", 'emotion_encoded': "Émotion"},
                 color='label')

fig.update_traces(mode='lines+markers+text', textposition='top center')
fig.show()

df_emotions_MF['en_text']

import plotly.graph_objects as go
import pandas as pd

# Exemple de df_emotions_MF
# df_emotions = pd.DataFrame({
#     'line_number': [0,1,2,3,…],
#     'score': [0.9,0.75,0.6,0.85,…],
#     'label': ['joy','sadness','anger','joy',…]
# })

# Encodage numérique des labels (optionnel, Plotly se débrouille aussi avec les strings)
df_emotions_MF['label_code'] = pd.Categorical(df_emotions_MF['label']).codes

# Créer la figure
fig = go.Figure()

# 1) Tracer la ligne grise unique qui connecte tous les points dans l'ordre
fig.add_trace(go.Scatter(
    x=df_emotions_MF['line_number'],
    y=df_emotions_MF['score'],
    mode='lines',
    line=dict(color='lightgrey', width=2),
    showlegend=False,
    hoverinfo='skip'
))

# 2) Ajouter les points colorés par émotion
fig.add_trace(go.Scatter(
    x=df_emotions_MF['line_number'],
    y=df_emotions_MF['score'],
    mode='markers',
    marker=dict(
        size=10,
        color=df_emotions_MF['label_code'],
        colorscale='Earth',
        cmin=0,
        cmax=df_emotions_MF['label_code'].max(),
        colorbar=dict(title="Emotion code"),
        line=dict(width=1, color='black')
    ),
    customdata=df_emotions_MF[['en_text', 'label']],  # 👈 pass both values for hover
    hovertemplate="""
    <b>Line %{x}</b><br>
    Emotion Score: %{y:.2f}<br>
    Emotion: %{customdata[1]}<br>
    <i>%{customdata[0]}</i><extra></extra>
    """
))

# Mise en page
fig.update_layout(
    title="Trajectoire émotionnelle (connected scatterplot) - Marie de France",
    xaxis_title="Numéro de vers",
    yaxis_title="Score de l’émotion",
    template="plotly_white",
    width=800, height=500,
    showlegend=False,
    plot_bgcolor='oldlace',
    paper_bgcolor='oldlace'
)

fig.show()

# Save the plot as an HTML file
fig.write_html("/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/connectedscatterplot1line3.html")

# Charger le poème à partir d'un fichier texte
with open('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Anne_Comnene_Alexiade.txt', 'r', encoding='utf-8') as file:
    Anne_Comnene_Alexiade = file.read()
#print(Anne_Comnene_Alexiade[:1500])

# Tokenisation et nettoyage
import re
cleaned_poem_AC = re.sub(r'\s+', ' ', Anne_Comnene_Alexiade).strip()  # Nettoyage des espaces multiples
cleaned_poem_AC = re.sub(r'[^\w\s,.\-:;!?«»]', '', Anne_Comnene_Alexiade)  # Garder des signes de ponctuation spécifiques


# Vectorisation (par exemple, TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=100)
tfidf_matrix = vectorizer.fit_transform([cleaned_poem_AC])

# Appliquer l'analyse NLP pour émotions et thèmes
from transformers import pipeline
emotion_model2 = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", top_k=1)
emotion2 = emotion_model2(cleaned_poem_AC)

print(f"Emotion détectée : {emotion2}")

# Charger le poème à partir d'un fichier texte
with open('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Hildegarde_O_clarissima_Mater.txt', 'r', encoding='utf-8') as file:
    Hildegarde_O_clarissima_Mater = file.read()
#print(Hildegarde_O_clarissima_Mater[:1500])

# Tokenisation et nettoyage
import re
cleaned_poem_HB = re.sub(r'\s+', ' ', Marie_de_France_Lai_du_Chevrefeuille).strip()  # Nettoyage des espaces multiples
cleaned_poem_HB = re.sub(r'[^\w\s,.\-:;!?«»]', '', Marie_de_France_Lai_du_Chevrefeuille)  # Garder des signes de ponctuation spécifiques


# Vectorisation (par exemple, TF-IDF)
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=100)
tfidf_matrix = vectorizer.fit_transform([cleaned_poem_HB])

# Appliquer l'analyse NLP pour émotions et thèmes
from transformers import pipeline
emotion_model3 = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", top_k=1)
emotion3 = emotion_model3(cleaned_poem_HB)

print(f"Emotion détectée : {emotion3}")

import re
import pandas as pd
from transformers import pipeline
import plotly.graph_objects as go
import plotly.express as px

# 1) Pipelines NLP
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en", device=-1)
emotion_model = pipeline("text-classification",
                         model="j-hartmann/emotion-english-distilroberta-base",
                         top_k=1,
                         device=-1)

def process_poem(path, poet_name):
    # charge et nettoie
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    # garder retours à la ligne et ponctuations choisies
    text = re.sub(r'[^\w\s,.\-:;!?«»\n]', '', text)
    lines = [l.strip() for l in text.split('\n') if l.strip()]

    data = []
    # batcher la traduction peut être plus rapide si nombreuses lignes
    translations = translator(lines, max_length=200, batch_size=8)
    en_lines = [t['translation_text'] for t in translations]

    for i, (fr, en) in enumerate(zip(lines, en_lines)):
        raw = emotion_model(en)
        first = raw[0]
        result = first[0] if isinstance(first, list) else first

        data.append({
            'poet': poet_name,
            'line_number': i,
            'fr_text': fr,
            'en_text': en,
            'label': result['label'],
            'score': result['score']
        })
    return pd.DataFrame(data)

# 2) Traiter les 3 poèmes
df_marie   = process_poem('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Marie_de_France_Lai_du_Chevrefeuille.txt', 'Marie de France')
df_anne    = process_poem('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Anne_Comnene_Alexiade.txt',        'Anne Comnène')
df_hilde   = process_poem('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Hildegarde_O_clarissima_Mater.txt','Hildegarde von Bingen')

df_all = pd.concat([df_marie, df_anne, df_hilde], ignore_index=True)

# 3) Encodage des émotions
df_all['label_code'] = pd.Categorical(df_all['label']).codes
n_codes = df_all['label_code'].nunique()

# Palette Set2
set2 = px.colors.qualitative.Set2

# 4) Tracé
fig = go.Figure()

# a) Lignes grises, une par poème
for poet, group in df_all.groupby('poet'):
    fig.add_trace(go.Scatter(
        x=group['line_number'],
        y=group['score'],
        mode='lines',
        line=dict(color='lightgrey', width=2),
        name=f"{poet} (path)",
        showlegend=False
    ))

# b) Points colorés par émotion, symboles distincts par poète
symbols = {'Marie de France': 'circle',
           'Anne Comnène':    'diamond',
           'Hildegarde von Bingen': 'square'}

for poet, group in df_all.groupby('poet'):
    fig.add_trace(go.Scatter(
        x=group['line_number'],
        y=group['score'],
        mode='markers',
        marker=dict(
            symbol=symbols[poet],
            size=10,
            color=group['label_code'],
            colorscale=set2,
            cmin=0,
            cmax=n_codes-1,
            line=dict(width=1, color='black')
        ),
        name=poet,
        text=group['label'],
        hovertemplate=(
            "<b>%{text}</b><br>"
            "Poète : " + poet + "<br>"
            "Ligne : %{x}<br>"
            "Score : %{y:.2f}<extra></extra>"
        )
    ))

fig.update_layout(
    title="Trajectoire émotionnelle des trois poèmes",
    xaxis_title="Numéro de vers",
    yaxis_title="Score émotionnel",
    legend_title="Poétesse",
    template="plotly_white",
    width=1500, height=550
)

fig.show()

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import plotly.graph_objects as go
import plotly.express as px
import re

df = df_all

# 2) Vectorisation et réduction de dimension
tfidf = TfidfVectorizer(max_features=50)
X_tfidf = tfidf.fit_transform(df['en_text']).toarray()
pca = PCA(n_components=2)
components = pca.fit_transform(X_tfidf)
df['x'] = components[:, 0]
df['y'] = components[:, 1]

# 3) Clustering
kmeans = KMeans(n_clusters=3, random_state=42)
df['cluster'] = kmeans.fit_predict(components)

# 4) Préparer df_all pour le plotting
df_all = df.copy()
df_all['line_number'] = df_all.groupby('poet').cumcount()
df_all['score'] = df_all['cluster'] / df_all['cluster'].max()  # pour l'exemple

# 5) Mapping des couleurs et symboles
emotion_list = df_all['cluster'].unique().tolist()
palette_emotion = px.colors.qualitative.Plotly
emotion_colors = {lab: palette_emotion[i % len(palette_emotion)]
                  for i, lab in enumerate(emotion_list)}

poem_list = df_all['poet'].unique().tolist()
palette_lines = px.colors.qualitative.Dark24
line_colors = {poem: palette_lines[i % len(palette_lines)]
               for i, poem in enumerate(poem_list)}

symbol_map = {
    'Marie de France': 'circle',
    'Anne Comnène': 'diamond',
    'Hildegarde von Bingen': 'square'
}

# 6) Création du graphique
fig = go.Figure()
for poem_name, group in df_all.groupby('poet'):
    poet_name = group['poet'].iloc[0]
    # tracé connecté + markers colorés par cluster
    fig.add_trace(go.Scatter(
        x=group['line_number'],
        y=group['score'],
        mode='lines+markers',
        line=dict(color=line_colors[poem_name], width=2),
        marker=dict(
            symbol=symbol_map[poet_name],
            size=10,
            color=[emotion_colors[c] for c in group['cluster']]
        ),
        name=poem_name,
        hovertemplate=(
            "Poème: " + poem_name + "<br>" +
            "Poétesse: " + poet_name + "<br>" +
            "Ligne %{x}<br>" +
            "Cluster: %{marker.color}<extra></extra>"
        )
    ))
    # annotation début
    start = group.iloc[0]
    fig.add_annotation(
        x=start['line_number'], y=start['score'],
        text=poem_name,
        showarrow=True, arrowhead=2,
        font=dict(color=line_colors[poem_name], size=12),
        ax=-20, ay=-20
    )
    # annotation fin
    end = group.iloc[-1]
    fig.add_annotation(
        x=end['line_number'], y=end['score'],
        text=poet_name,
        showarrow=True, arrowhead=2,
        font=dict(color=line_colors[poem_name], size=12),
        ax=20, ay=20
    )

fig.update_layout(
    title="Trajectoire émotionnelle des trois poèmes",
    xaxis_title="Numéro de vers",
    yaxis_title="Score d'exemple",
    legend_title="Poèmes",
    template="plotly_white",
    width=1500, height=550
)

fig.show()

print(df_all.columns)

import re
import pandas as pd
from transformers import pipeline
import plotly.graph_objects as go
import plotly.express as px

# 1) Pipelines NLP
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en", device=-1)
emotion_model = pipeline("text-classification",
                         model="j-hartmann/emotion-english-distilroberta-base",
                         top_k=1,
                         device=-1)

def process_poem(path, poet_name):
    # charge et nettoie
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    # garder retours à la ligne et ponctuations choisies
    text = re.sub(r'[^\w\s,.\-:;!?«»\n]', '', text)
    lines = [l.strip() for l in text.split('\n') if l.strip()]

    data = []
    # batcher la traduction peut être plus rapide si nombreuses lignes
    translations = translator(lines, max_length=200, batch_size=8)
    en_lines = [t['translation_text'] for t in translations]

    for i, (fr, en) in enumerate(zip(lines, en_lines)):
        raw = emotion_model(en)
        first = raw[0]
        result = first[0] if isinstance(first, list) else first

        data.append({
            'poet': poet_name,
            'line_number': i,
            'fr_text': fr,
            'en_text': en,
            'label': result['label'],
            'score': result['score']
        })
    return pd.DataFrame(data)

# 2) Traiter les 3 poèmes
df_marie   = process_poem('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Marie_de_France_Lai_du_Chevrefeuille.txt', 'Marie de France')
df_anne    = process_poem('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Anne_Comnene_Alexiade.txt',        'Anne Comnène')
df_hilde   = process_poem('/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Hildegarde_O_clarissima_Mater.txt','Hildegarde von Bingen')

df_all = pd.concat([df_marie, df_anne, df_hilde], ignore_index=True)

# 3) Encodage des émotions
df_all['label_code'] = pd.Categorical(df_all['label']).codes
n_codes = df_all['label_code'].nunique()

# Palette Set2
set2 = px.colors.qualitative.Set2

# 4) Tracé
fig = go.Figure()

# a) Lignes grises, une par poème
for poet, group in df_all.groupby('poet'):
    fig.add_trace(go.Scatter(
        x=group['line_number'],
        y=group['score'],
        mode='lines',
        line=dict(color='lightgrey', width=2),
        name=f"{poet} (path)",
        showlegend=False
    ))

# b) Points colorés par émotion, symboles distincts par poète
symbols = {'Marie de France': 'circle',
           'Anne Comnène':    'diamond',
           'Hildegarde von Bingen': 'square'}

for poet, group in df_all.groupby('poet'):
    fig.add_trace(go.Scatter(
        x=group['line_number'],
        y=group['score'],
        mode='markers',
        marker=dict(
            symbol=symbols[poet],
            size=10,
            color=group['label_code'],
            colorscale=set2,
            cmin=0,
            cmax=n_codes-1,
            line=dict(width=1, color='black')
        ),
        name=poet,
        text=group['label'],
        hovertemplate=(
            "<b>%{text}</b><br>"
            "Poète : " + poet + "<br>"
            "Ligne : %{x}<br>"
            "Score : %{y:.2f}<extra></extra>"
        )
    ))

fig.update_layout(
    title="Trajectoire émotionnelle des trois poèmes",
    xaxis_title="Numéro de vers",
    yaxis_title="Score émotionnel",
    legend_title="Poétesse",
    template="plotly_white",
    width=1500, height=550
)

fig.show()

df_all

import re
import pandas as pd
from transformers import pipeline
import plotly.graph_objects as go
import plotly.express as px

# 1) Pipelines NLP
translator = pipeline("translation", model="Helsinki-NLP/opus-mt-fr-en", device=-1)
emotion_model = pipeline("text-classification",
                         model="j-hartmann/emotion-english-distilroberta-base",
                         top_k=1,
                         device=-1)

def process_poem(path, poet_name, poem_title):
    # charge et nettoie
    with open(path, 'r', encoding='utf-8') as f:
        text = f.read()
    # garder retours à la ligne et ponctuations choisies
    text = re.sub(r'[^\w\s,.\-:;!?«»\n]', '', text)
    lines = [l.strip() for l in text.split('\n') if l.strip()]

    data = []
    # batcher la traduction
    translations = translator(lines, max_length=200, batch_size=8)
    en_lines = [t['translation_text'] for t in translations]

    for i, (fr, en) in enumerate(zip(lines, en_lines)):
        raw = emotion_model(en)
        first = raw[0]
        result = first[0] if isinstance(first, list) else first

        data.append({
            'poet': poet_name,
            'poem': poem_title,
            'line_number': i,
            'fr_text': fr,
            'en_text': en,
            'label': result['label'],
            'score': result['score']
        })
    return pd.DataFrame(data)

# 2) Traiter les 3 poèmes
df_marie = process_poem(
    '/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Marie_de_France_Lai_du_Chevrefeuille.txt',
    'Marie de France', 'Lai du Chèvrefeuille')
df_anne = process_poem(
    '/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Anne_Comnene_Alexiade.txt',
    'Anne Comnène', 'Alexiade')
df_hilde = process_poem(
    '/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/Hildegarde_O_clarissima_Mater.txt',
    'Hildegarde von Bingen', 'O clarissima Mater')

df_all = pd.concat([df_marie, df_anne, df_hilde], ignore_index=True)

# 3) Encodage des émotions
df_all['label_code'] = pd.Categorical(df_all['label']).codes
n_codes = df_all['label_code'].nunique()

# Palette
set2 = px.colors.qualitative.Set2
d3_colors = px.colors.qualitative.D3

# 4) Tracé
fig = go.Figure()

# a) Lignes colorées par poème
for i, (poem, group) in enumerate(df_all.groupby('poem')):
    fig.add_trace(go.Scatter(
        x=group['line_number'],
        y=group['score'],
        mode='lines',
        line=dict(color=d3_colors[i % len(d3_colors)], width=2),
        name=poem,
        hoverinfo='skip',
        showlegend=False
    ))

# b) Points colorés par émotion, symboles par poétesse
symbols = {
    'Marie de France': 'circle',
    'Anne Comnène': 'diamond',
    'Hildegarde von Bingen': 'square'
}


medieval_colorscale = [
    [0.0, "#5B3A29"],   # Sepia ink / Earthy brown
    [0.17, "#9E1316"],  # Madder red
    [0.33, "#3F704D"],  # Verdigris green
    [0.5, "#C19A6B"],   # Light parchment ochre
    [0.67, "#4A5D23"],  # Olive moss green
    [0.83, "#6B4226"],  # Burnt umber
    [1.0, "#2E1D0D"]    # Walnut ink dark brown
]

for poet, group in df_all.groupby('poet'):
    fig.add_trace(go.Scatter(
        x=group['line_number'],
        y=group['score'],
        mode='markers',
        marker=dict(
            symbol=symbols[poet],
            size=10,
            color=group['label_code'],
            colorscale=medieval_colorscale,  # 👈 Custom medieval scale
            cmin=0,
            cmax=n_codes-1,
            line=dict(width=1, color='black')
        ),
        name=poet,
        text=group['label'],  # Emotion
        customdata=group[['poem', 'en_text']].values,  # 👈 REQUIRED
        hovertemplate=(
            "<b>%{text}</b><br>"            # Emotion label
            "Poet: " + poet + "<br>"        # Static name
            "Poem: %{customdata[0]}<br>"    # Poem title
            "Score: %{y:.2f}<br>"       # Score
            "Verse: %{customdata[1]}<br>"   # English verse
            "<extra></extra>"
        )
    ))

fig.update_layout(
    title="Trajectoire émotionnelle des trois poèmes",
    xaxis_title="Numéro de vers",
    yaxis_title="Score émotionnel",
    legend_title="Poétesse",
    template="plotly_white",
    width=1500,
    height=550,
    plot_bgcolor='oldlace',
    paper_bgcolor='oldlace'
)

fig.show()
# Save the plot as an HTML file
fig.write_html("/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/3poems_trajectory.html")

from sklearn.cluster import KMeans

# Add KMeans clusters based on emotional score
kmeans = KMeans(n_clusters=3, random_state=42)
df_all['intensity_cluster'] = kmeans.fit_predict(df_all[['score']])

# Reassign cluster labels by average intensity
cluster_order = df_all.groupby('intensity_cluster')['score'].mean().sort_values().index
cluster_map = {old: new for new, old in enumerate(cluster_order)}
df_all['intensity_cluster'] = df_all['intensity_cluster'].map(cluster_map)

import plotly.express as px

fig = px.scatter(
    df_all,
    x="line_number",
    y="score",
    color="intensity_cluster",
    symbol="poet",
    color_discrete_sequence=["red", "gold", "white"],  # or your medieval palette
    hover_data=["poet", "poem", "label", "en_text"],
    title="Clustering des vers par intensité émotionnelle"
)

fig.update_traces(marker=dict(size=10, line=dict(width=1, color='black')))
fig.update_layout(plot_bgcolor='oldlace', paper_bgcolor='oldlace')

fig.show()
# Save the plot as an HTML file
fig.write_html("/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/3poems_cluster.html")

clustered_poems = {}

for cluster_id in sorted(df_all['intensity_cluster'].unique()):
    verses = df_all[df_all['intensity_cluster'] == cluster_id] \
        .sort_values(by=['poet', 'poem', 'line_number'])

    grouped = verses.groupby(['poet', 'poem'])['fr_text'].apply(lambda lines: '\n'.join(lines))
    clustered_poems[cluster_id] = grouped

for cluster_id, poems in clustered_poems.items():
    print(f"\n\n### Cluster {cluster_id} (Intensity Level {cluster_id}) ###")
    for (poet, title), poem in poems.items():
        print(f"\n--- {title} by {poet} ---\n")
        print(poem)

import plotly.graph_objects as go
from scipy.spatial import ConvexHull
import numpy as np

# Calculer les convex hulls pour chaque cluster
fig = go.Figure()

# Tracer les points et les lignes comme précédemment
for poet, group in df_all.groupby('poet'):
    fig.add_trace(go.Scatter(
        x=group['line_number'],
        y=group['score'],
        mode='markers',
        marker=dict(
            symbol=symbols[poet],
            size=10,
            color=group['intensity_cluster'],
            colorscale='Earth',  # Ou une palette médievale personnalisée
            cmin=0,
            cmax=2,  # Nous avons 3 clusters
            line=dict(width=1, color='black')
        ),
        name=poet,
        text=group['label'],
        hovertemplate=(
            "<b>%{text}</b><br>"            # Emotion label
            "Poet: " + poet + "<br>"        # Static name
            "Poem: %{customdata[0]}<br>"    # Poem title
            "Score: %{y:.2f}<br><br>"       # Score
            "Verse: %{customdata[1]}<br>"   # English verse
            "<extra></extra>"
        ),
        customdata=group[['poem', 'en_text']]
    ))

# Calculer et tracer les convex hulls pour chaque cluster
for cluster_id in range(3):  # Pour 3 clusters
    cluster_data = df_all[df_all['intensity_cluster'] == cluster_id]
    points = cluster_data[['line_number', 'score']].values
    if len(points) >= 3:  # Au moins 3 points nécessaires pour former un convex hull
        hull = ConvexHull(points)
        hull_points = np.append(points[hull.vertices], [points[hull.vertices][0]], axis=0)

        fig.add_trace(go.Scatter(
            x=hull_points[:, 0],
            y=hull_points[:, 1],
            fill='toself',
            fillcolor=f'rgba({255-30*cluster_id}, {100+30*cluster_id}, 0, 0.3)',  # Couleur semi-transparente par cluster
            line=dict(color=f'rgba({255-30*cluster_id}, {100+30*cluster_id}, 0, 1)', width=2),
            name=f"Cluster {cluster_id} - Intensity",
            showlegend=False
        ))

fig.update_layout(
    title="Trajectoire émotionnelle des trois poèmes avec clusters par intensité",
    xaxis_title="Numéro de vers",
    yaxis_title="Score émotionnel",
    legend_title="Poétesse",
    template="plotly_white",
    width=1500,
    height=550,
    plot_bgcolor='oldlace',
    paper_bgcolor='oldlace'
)

fig.show()
# Save the plot as an HTML file
fig.write_html("/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/3poems_cluster.html")



clustered_poems = {}

# Créer une version pour chaque cluster
for cluster_id in sorted(df_all['intensity_cluster'].unique()):
    verses = df_all[df_all['intensity_cluster'] == cluster_id] \
        .sort_values(by=['poet', 'poem', 'line_number'])

    # Recréation des poèmes par cluster
    grouped = verses.groupby(['poet', 'poem'])['fr_text'].apply(lambda lines: '\n'.join(lines))
    clustered_poems[cluster_id] = grouped

# Afficher ou exporter les poèmes
for cluster_id, poems in clustered_poems.items():
    print(f"\n\n### Cluster {cluster_id} (Intensity Level {cluster_id}) ###")
    for (poet, title), poem in poems.items():
        print(f"\n--- {title} by {poet} ---\n")
        print(poem)

# Define cluster names
cluster_names = {0: 'Chill', 1: 'Tempered', 2: 'Intense'}

# Recreate poems by cluster
clustered_poems = {}
for cluster_id in sorted(df_all['intensity_cluster'].unique()):
    verses = df_all[df_all['intensity_cluster'] == cluster_id] \
        .sort_values(by=['poet', 'poem', 'line_number'])

    # Recreate the poem text for each cluster
    grouped = verses.groupby(['poet', 'poem'])['fr_text'].apply(lambda lines: '\n'.join(lines))
    clustered_poems[cluster_names[cluster_id]] = grouped

# Prepare HTML content for each cluster
html_content = ""
for cluster_name, poems in clustered_poems.items():
    html_content += f"<h2>{cluster_name} Poem</h2>"
    for (poet, title), poem in poems.items():
        html_content += f"<div style='border: 2px solid #8B4513; padding: 15px; margin: 10px; font-family: 'Garamond', serif; background-color: #F4E1D2;'>"
        html_content += f"<h3>{title} by {poet}</h3>"
        html_content += f"<pre>{poem}</pre>"
        html_content += "</div>"

from google.colab import drive
import os

# Mount Google Drive
drive.mount('/content/drive')

# Define the path where the file will be saved
html_file_path = '/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/poems_by_clusters.html'

# Save the HTML content to a file on Google Drive
with open(html_file_path, 'w', encoding='utf-8') as f:
    f.write(html_content)

# Verify the file is saved
print(f"HTML file saved successfully at: {html_file_path}")

# Adding parchment scroll effect using CSS
html_header = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Emotional Clusters of Poems</title>
    <style>
        body {
            font-family: 'Georgia', serif;
            background-color: #f5f0e1;
            padding: 20px;
        }
        h2 {
            text-align: center;
            color: #8B4513;
            font-size: 30px;
            border-bottom: 3px solid #8B4513;
        }
        .scroll-container {
            display: flex;
            justify-content: space-around;
            margin-top: 20px;
        }
        .scroll {
            width: 30%;
            border: 2px solid #8B4513;
            padding: 10px;
            margin: 10px;
            background-color: #f4e1d2;
            font-family: 'Garamond', serif;
            overflow-y: scroll;
            height: 400px;
        }
        pre {
            white-space: pre-wrap;
            word-wrap: break-word;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <h1 style="text-align:center; color: #8B4513;">Poems by Emotional Clusters</h1>
    <div class="scroll-container">
"""

html_footer = """
    </div>
</body>
</html>
"""

# Combine everything into a full HTML file
full_html_content = html_header + html_content + html_footer

fig.write_html("/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/3poems_cluster.html")

html_file_path = "/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/poems_by_clusters.html"

# Save to an HTML file

with open('poems_by_clusters.html', 'w', encoding='utf-8') as f:
    f.write(full_html_content)

print("HTML file has been saved as 'poems_by_clusters.html'")









df_all.groupby('poet')['score'].mean().sort_values(ascending=False)
#df_all.groupby('poet')['score'].max().sort_values(ascending=False)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
sns.boxplot(data=df_all, x='poet', y='score', palette="Set2")
plt.title("Distribution des scores émotionnels par poétesse")
plt.ylabel("Score émotionnel (intensité)")
plt.xlabel("Poétesse")
plt.show()

"""📈 Interprétation attendue
Si une poétesse a une moyenne élevée → émotions plus souvent intenses ou claires.

Si une poétesse a un max plus élevé → quelques pics émotionnels très forts.

Une boîte plus étroite → émotions plus uniformes, moins de variation.

Une boîte plus étendue ou des outliers → poème plus émotionnellement contrasté.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Violin plot pour visualiser la distribution des scores émotionnels par poétesse
plt.figure(figsize=(12, 6))
sns.violinplot(data=df_all, x='poet', y='score', palette="Set2", inner='box')
plt.title("Distribution des scores émotionnels par poétesse (Violin Plot)")
plt.ylabel("Score émotionnel (intensité)")
plt.xlabel("Poétesse")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

"""Voici le violin plot ! Il montre la distribution des scores émotionnels pour chaque poétesse. On peut voir :

- Marie de France a des scores plutôt étalés, avec quelques émotions très marquées.

- Anne Comnène semble plus contenue émotionnellement, avec une distribution plus centrée.

- Hildegarde von Bingen a une large variation aussi, mais avec un pic d’intensité plus marqué sur certaines lignes.
"""

# Violin plot interactif avec annotations par poétesse
fig_violin = px.violin(df_all,
                       x="poet",
                       y="score",
                       color="poet",
                       box=True,
                       points="all",
                       hover_data=["fr_text", "label"],
                       color_discrete_sequence=px.colors.qualitative.Set2)

# Mise à jour du layout avec annotations
fig_violin.update_layout(
    title="Distribution des intensités émotionnelles par poétesse",
    yaxis_title="Score émotionnel",
    xaxis_title="Poétesse",
    template="plotly_white",
    width=1000,
    height=600,
    showlegend=False
)

# Ajouter des annotations personnalisées pour chaque violon
annotations = [
    dict(x='Marie de France', y=1.05, text="Émotions marquées mais variées", showarrow=False, font=dict(size=12)),
    dict(x='Anne Comnène', y=1.05, text="Plutôt modérée", showarrow=False, font=dict(size=12)),
    dict(x='Hildegarde von Bingen', y=1.05, text="Grande intensité émotionnelle", showarrow=False, font=dict(size=12))
]
fig_violin.update_layout(annotations=annotations)

fig_violin.show()

import plotly.express as px

earthy_colors = ["#5B3A29", "#9E1316", "#3F704D"]  # brown, red, verdigris green

fig_violin = px.violin(
    df_all,
    x="poet",
    y="score",
    color="poet",
    box=True,
    points="all",
    hover_data=["fr_text", "label"],
    color_discrete_sequence=earthy_colors
)

fig_violin.update_layout(
    title="Distribution des intensités émotionnelles par poétesse",
    yaxis_title="Score émotionnel",
    xaxis_title="Poétesse",
    template="plotly_white",
    width=1000,
    height=600,
    showlegend=False,
    plot_bgcolor='oldlace',
    paper_bgcolor='oldlace',
    annotations=[
        dict(x='Marie de France', y=1.05, text="Émotions marquées mais variées", showarrow=False, font=dict(size=12)),
        dict(x='Anne Comnène', y=1.05, text="Plutôt modérée", showarrow=False, font=dict(size=12)),
        dict(x='Hildegarde von Bingen', y=1.05, text="Grande intensité émotionnelle", showarrow=False, font=dict(size=12))
    ]
)



fig_violin.show()
# Save the plot as an HTML file
fig_violin.write_html("/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/violin_poetess.html")

"""meme si les graphs son partfaits, nous ne voyons pas trop les cluster, ce qui etait l'objectif du challenge, peu etre qu'avec df_all on peut faire un scatterplot par emotion et intensite et regrouper en plusieurs clusters? ET tu m'aides a' preeenter tout ca sur une page github (avec un index html ou j'expliquerai chaque etape :)

"""

import pandas as pd
import matplotlib.pyplot as plt

# Your DataFrame
df = pd.DataFrame({
    "Word": ["love", "is", "a", "flame", "that", "burns", "unseen"],
    "Dim 1": [0.21, 0.05, -0.12, 0.53, -0.22, 0.67, 0.32],
    "Dim 2": [0.89, 0.72, 0.33, -0.12, 0.01, 0.03, -0.76],
    "Dim 3": [-0.45, 0.10, 0.44, 0.77, 0.13, -0.35, 0.44]
})
df.set_index("Word", inplace=True)

# Create the figure
fig, ax = plt.subplots(figsize=(6, 3))
ax.axis('off')
table = ax.table(cellText=df.values, colLabels=df.columns, rowLabels=df.index,
                 cellLoc='center', loc='center')
table.auto_set_font_size(False)
table.set_fontsize(10)
table.scale(1.2, 1.2)

# Save as image
plt.savefig("word_embeddings.jpg", dpi=300, bbox_inches='tight')

from sklearn.cluster import KMeans
import plotly.express as px

# On utilise KMeans pour créer les clusters en fonction des scores d'émotion
kmeans = KMeans(n_clusters=3, random_state=42)
df_all['cluster'] = kmeans.fit_predict(df_all[['score']])

# Scatterplot avec couleur par émotion et position par score d'intensité
fig = px.scatter(df_all,
                 x='line_number',
                 y='score',
                 color='label',
                 size_max=10,
                 color_discrete_map={emotion: color for emotion, color in zip(df_all['label'].unique(), px.colors.qualitative.Set2)},
                 title="Clusters d'émotions dans les poèmes")

# Ajout de clusters
fig.update_traces(marker=dict(size=10, opacity=0.6, line=dict(width=2, color='DarkSlateGrey')))
fig.update_layout(legend_title="Emotions", xaxis_title="Numéro de vers", yaxis_title="Score émotionnel")

# Affichage
fig.show()

from sklearn.cluster import KMeans
import plotly.express as px
import numpy as np

# Étape 1 : Clustering en fonction de l'intensité (scores)
kmeans = KMeans(n_clusters=3, random_state=42)
df_all['cluster'] = kmeans.fit_predict(df_all[['score']])

# Étape 2 : Analyse des clusters pour voir l'intensité moyenne de chaque émotion
cluster_summary = df_all.groupby(['cluster', 'label'])['score'].mean().reset_index()

# Trouver l'émotion la plus forte dans chaque cluster
dominant_emotion = cluster_summary.loc[cluster_summary.groupby('cluster')['score'].idxmax()]

# Affichage des résultats de clustering
fig = px.scatter(df_all,
                 x='line_number',
                 y='score',
                 color='label',
                 size_max=10,
                 color_discrete_map={emotion: color for emotion, color in zip(df_all['label'].unique(), px.colors.qualitative.Set2)},
                 title="Clusters d'intensité émotionnelle des poèmes",
                 hover_data=['poet'])

# Ajouter les clusters sur le graphique
fig.update_traces(marker=dict(size=10, opacity=0.6, line=dict(width=2, color='DarkSlateGrey')))

# Affichage de l'intensité émotionnelle par cluster
for cluster_num in dominant_emotion['cluster']:
    fig.add_annotation(
        x=cluster_num, y=dominant_emotion.loc[dominant_emotion['cluster'] == cluster_num, 'score'].values[0],
        text=f"Cluster {cluster_num}: {dominant_emotion.loc[dominant_emotion['cluster'] == cluster_num, 'label'].values[0]}",
        showarrow=True,
        arrowhead=2,
        font=dict(size=12, color='black'),
        align='center'
    )

fig.update_layout(
    xaxis_title="Numéro de vers",
    yaxis_title="Score émotionnel",
    legend_title="Emotions",
    template="plotly_white"
)

fig.show()

# Affichage des insights
print("Insights des clusters d'intensité émotionnelle :")
print(dominant_emotion)

import plotly.express as px

# Étape 1 : Calcul de l'intensité moyenne de chaque émotion
emotion_mean = df_all.groupby('label')['score'].mean().reset_index()
earthy_colors = [
    "#5B3A29",  # Earthy brown (sepia ink)
    "#9E1316",  # Deep red (madder)
    "#3F704D",  # Verdigris green
    "#C19A6B",  # Light ochre / parchment tan
    "#6B4226",  # Burnt umber
    "#4A5D23",  # Moss green / dark olive
    "#2E1D0D"   # Rich dark brown (walnut ink)
]
# Étape 2 : Créer un violin plot pour visualiser la distribution des scores par émotion
fig = px.violin(df_all,
                x='label',
                y='score',
                box=True,
                points='all',  # Afficher tous les points pour chaque émotion
                color='label',  # Colorier par émotion
                color_discrete_sequence=earthy_colors,
                title="Distribution de l'intensité émotionnelle par émotion",
                labels={'label': 'Émotion', 'score': 'Score émotionnel'},
                template='plotly_white')

fig.update_layout(
    title="Distribution de l'intensité émotionnelle par émotion",
    xaxis_title="Émotions",
    yaxis_title="Score émotionnel",
    plot_bgcolor='oldlace',
    paper_bgcolor='oldlace',
    showlegend=False
)

fig.show()


# Save the plot as an HTML file
fig.write_html("/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/violin_emotions.html")

import plotly.express as px

# Compter la fréquence de chaque émotion
emotion_counts = df_all['label'].value_counts().reset_index()
emotion_counts.columns = ['emotion', 'count']

# Tracer un barplot
fig = px.bar(emotion_counts,
             x='emotion',
             y='count',
             color='emotion',
             text='count',
             title="Fréquence des émotions détectées dans les trois textes",
             color_discrete_sequence=px.colors.qualitative.Set2)

fig.update_layout(
    xaxis_title="Émotion",
    yaxis_title="Nombre d'occurrences",
    template='plotly_white',
    width=500,
    height=400,
    showlegend=False,
    plot_bgcolor='oldlace',
    paper_bgcolor='oldlace'
)

fig.update_traces(textposition='outside')

fig.show()

# Save the plot as an HTML file
fig.write_html("/content/drive/MyDrive/30DayChartChallenge/datasets/corpus/emotion_frequencies4.html")

from sklearn.cluster import KMeans
import plotly.express as px

# On utilise KMeans pour créer les clusters en fonction des scores d'émotion
kmeans = KMeans(n_clusters=3, random_state=42)
df_all['cluster'] = kmeans.fit_predict(df_all[['score']])

# Scatterplot avec couleur par émotion et position par score d'intensité
fig = px.scatter(df_all,
                 x='line_number',
                 y='score',
                 color='label',
                 size_max=10,
                 color_discrete_map={emotion: color for emotion, color in zip(df_all['label'].unique(), px.colors.qualitative.Set2)},
                 title="Clusters d'émotions dans les poèmes")

# Ajout de clusters
fig.update_traces(marker=dict(size=10, opacity=0.6, line=dict(width=2, color='DarkSlateGrey')))
fig.update_layout(legend_title="Emotions", xaxis_title="Numéro de vers", yaxis_title="Score émotionnel")

# Affichage
fig.show()